# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-rds-replica
  description: Terraform module that provisions an RDS replica
  homepage: https://cloudposse.com/accelerate
  topics: rds, terraform, terraform-modue, aurora, mysql, postgres, slave, replica, readonly


